spring.application.name=transactions
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/${MYSQL_DATABASE:transactions}?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:n3u3da!}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:seed_data.sql
server.port=${SERVER_PORT:8085}
